# Development overrides
services:
  web:
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ../dist:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../data:/data:ro

  updater:
    image: node:24-slim
    volumes:
      - ./updater.js:/app/updater.js:ro
      - ../data:/data
    environment:
      - UPDATE_INTERVAL=43200000  # 12 hours
      - ANTHROPIC_API_KEY=${CCHISTORY_ANTHROPIC_API_KEY}

  livereload:
    image: node:alpine
    stop_grace_period: 1s
    working_dir: /app
    command: sh -c "npm install -g livereload && livereload /app/public --port 35729 --bind 0.0.0.0"
    volumes:
      - ../dist:/app/public